1. How to state the zudoku from table to code

In [ ]:
table = [None for x in range(1,10) for y in range(1,10)]